# this file is autogenerated by .github/workflows/update.yml
{
  url = "https://github.com/azuwis/nix-index-database/releases/download/2025-11-16-034113/index-";
  hashes = {
    x86_64-linux = "sha256-z84idA0ZG7zQ1pHlUBHpKAJGmgb8IsD7nDoICReO50w=";
    aarch64-linux = "sha256-xGwQNul6VEUWQJVC8c4Pr+5GBBofbNv9sL+YQyW7Vpg=";
    x86_64-darwin = "sha256-OqCV7Kw86xFixQter0osOHYxvEXXGs1idpzbU6MFHsQ=";
    aarch64-darwin = "sha256-XoGKgcqg2zCvE+BadmVMxFxIfGS5TpPwyrruFQVGYkw=";
    x86_64-linux-small = "sha256-K5+BOVur9qHM26iTFl5i/DVkU2VS9plDZjPOLTxX9xc=";
    aarch64-linux-small = "sha256-ByzwSFaly4pTT9pAuD4uI1tS6zO00ruFUVHnoMZzjKI=";
    x86_64-darwin-small = "sha256-Zuqf7NTUnlN+s/rRtkExRm3KI6V+gDSS5rT0kMnklc4=";
    aarch64-darwin-small = "sha256-02zrVdAP6HkTjePuEqcro0jI41gg3EyZY7p8uxBh9HU=";
    x86_64-linux-stable = "sha256-rzQPvzMf+FHpyuRc9Mekya5NtP3cQRV8M3dHISt0tUM=";
    aarch64-linux-stable = "sha256-4V28Y8T5r8VIKN0ZqnsKflJzCB5LgdtZdfjbfR64Pak=";
    x86_64-darwin-stable = "sha256-iBYiQUZxLj3D0LFt7V1dpQRhMT/o0m2SfzU583Khnzk=";
    aarch64-darwin-stable = "sha256-u06yqtuYaRJVJHPn95BK9YjfBC4vJHE6gKJtEVt993Q=";
    x86_64-linux-stable-small = "sha256-TxFxSBM0hUcbiF0ZWh+rLH2Qaarmbhj7xTxcvq+KVP8=";
    aarch64-linux-stable-small = "sha256-rr1XBSf7qEZw/OLJS4XRu0oR2yrtdpCXnR80Uu31U1g=";
    x86_64-darwin-stable-small = "sha256-tCz/auSY1u28Z04i59lTOtEzlDms5AWq1156brPjIa4=";
    aarch64-darwin-stable-small = "sha256-I/z9AE/LrwsO3Sla0z4hfoL7jUKDt579C3ErpIzeLuY=";
  };
}
