# this file is autogenerated by .github/workflows/update.yml
{
  url = "https://github.com/azuwis/nix-index-database/releases/download/2026-05-10-055244/index-";
  hashes = {
    x86_64-linux = "sha256-1GWQNNKzRKT6K4Mq1/2N+H5cVsH4jVtOD6xR11lMkBo=";
    aarch64-linux = "sha256-3Hu2VAVqwWaeeGsw0Xs5HnhDEvg4HSxhtVO9fXmwFGw=";
    x86_64-darwin = "sha256-Yad8HSKj7Y8PZpnL4m5ObHXj7DGIc31FGYmdzXtKai8=";
    aarch64-darwin = "sha256-u5eTcn9J/tkGx8bGeY2MBc+SO247+qXavT92d8vg9v4=";
    x86_64-linux-small = "sha256-oqixnrpgeAb9kauaW8Sykn60/qrUWAhIZpLKdlHxQrI=";
    aarch64-linux-small = "sha256-0r5s1Kp80TNE0BAeGsfPpVVMqg1KNLTddHEgqNKQLTM=";
    x86_64-darwin-small = "sha256-mr+2ta9RhZMz+xcnpl3rI2nu9dhw0lMsWgDeDYF0MVU=";
    aarch64-darwin-small = "sha256-VmT9ELxo5jznCd2GxzD1a/yDteHOiVnR7Ez7pERrNM8=";
    x86_64-linux-stable = "sha256-KAvubfZHlavFzsL38LLDGyDAQINo/wSmsnoUHD4G9RE=";
    aarch64-linux-stable = "sha256-sAFxwhrl7lbIoZPm3jMsE4lAtQPyq4jSw+BCtfXbHNU=";
    x86_64-darwin-stable = "sha256-QR07ZCF23Jp+pXEVANcRFKJB/g+NH9nNjo2AxXiGmRc=";
    aarch64-darwin-stable = "sha256-beZ6fqbfIGJGuYw7JNR7Gb3mROxM5AAvLTLGdu41G78=";
    x86_64-linux-stable-small = "sha256-JiPJC+XCWq7UP85xveJ5Aw4wZKMzdtT2yrekgxCDeO4=";
    aarch64-linux-stable-small = "sha256-enMkM6dcDf3pIkh1YlgqVECJTA5jEzl/h7HRy88yjAE=";
    x86_64-darwin-stable-small = "sha256-p3lpYnUaDrsur78a4uO9gfLqH0/DPfAMdoIWZrHQVeA=";
    aarch64-darwin-stable-small = "sha256-eqEkcNHkY7ccYelKSvkSngMFhOkYClbo0Tm2nKlhgDI=";
  };
}
