# this file is autogenerated by .github/workflows/update.yml
{
  url = "https://github.com/azuwis/nix-index-database/releases/download/2026-01-11-040438/index-";
  hashes = {
    x86_64-linux = "sha256-wts68NBT/teWoFYIYPbH9JUKfrWhic1EriYcHG74BQI=";
    aarch64-linux = "sha256-BCqYN54nBUqnjk2egPhyXdfiZA26tMKpM6FsEDm/H2s=";
    x86_64-darwin = "sha256-kNvNt/p9mdZd/SKD/wxmZQYfuA2I8/etZCVgnqGlYyU=";
    aarch64-darwin = "sha256-xecZN1pnSN7/f+UmLKifUNlVAtqEOgOq6IVFnrc34SI=";
    x86_64-linux-small = "sha256-QVkp+H6dD6jDg4MqmlPMtvHUKBgufnyiKKXZxcJCfsY=";
    aarch64-linux-small = "sha256-9f4tq/KvT502fQtfmV3AWxPESDYj5Va5ymw9SCI+W00=";
    x86_64-darwin-small = "sha256-NBU9mI4bhVUG3qbMixLGj6D5E43H+iOdD6NwNLf1WOk=";
    aarch64-darwin-small = "sha256-T/AF6LWoVWOfYpdG6Z6HBU31FTbc7j/alrgvds5ElQ8=";
    x86_64-linux-stable = "sha256-cJzpC9VlfvbXL/Picqz18rpZ8tabjonn+3gZaloOBZw=";
    aarch64-linux-stable = "sha256-PM5jXwgGYE3KOTdkqNNaIxbKj9Nnr7b/1v+QkC8K6Qk=";
    x86_64-darwin-stable = "sha256-tCbOgt2uKtAaM0PoI8ubMRwhzacdePSziRnd+XnpJsk=";
    aarch64-darwin-stable = "sha256-IGs13ORN7J2aS/fiQwML3KDKQjQL2NAS27DuFNLm4wI=";
    x86_64-linux-stable-small = "sha256-1G+fBuVR0TuY1kJjlRvJg/LZmajDo6kdMBJdBKh4EVE=";
    aarch64-linux-stable-small = "sha256-DF3Kl2H2FrNs07idrW6RfKRR8fAxx2NZAeeEfkLtI8Y=";
    x86_64-darwin-stable-small = "sha256-TUsNp7V3znkPgx51/S2IZSXktkutJ+MoYjLTyXUxQxQ=";
    aarch64-darwin-stable-small = "sha256-9dOeYrSBe9uO11e/JtJCItADrAFVrDjB9o8RnE00f34=";
  };
}
